const userData = [
  {
    id: 1,
    name: "alexrivera",
    role: "Pro Athlete",
    totalWorkouts: 150,
    isActive: true,
    lastLogin: "2024-06-01T10:24:00Z",
    totalHours: 280,
    streak: 12,
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    name: "sarahchen",
    role: "AI Trainer",
    totalWorkouts: 90,
    isActive: false,
    lastLogin: "2024-05-28T09:15:00Z",
    totalHours: 190,
    streak: 6,
    avatar: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: 3,
    name: "marcusknight",
    role: "Elite Member",
    totalWorkouts: 120,
    isActive: true,
    lastLogin: "2024-06-01T08:45:00Z",
    totalHours: 250,
    streak: 9,
    avatar: "https://i.pravatar.cc/150?img=3",
  } ,
  {
    id: 4,
    name: "elenarodriguez",
    role: "Data Scientist",
    totalWorkouts: 60,
    isActive: true,
    lastLogin: "2024-06-01T12:30:00Z",
    totalHours: 120,
    streak: 4,
    avatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: 5,
    name: "jordansmith",
    role: "General User",
    totalWorkouts: 30,
    isActive: false,
    lastLogin: "2024-05-30T14:00:00Z",
    totalHours: 60,
    streak: 2,
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 6,
    name: "priyapatel",
    role: "Nutritionist",
    totalWorkouts: 110,
    isActive: true,
    lastLogin: "2024-06-01T07:20:00Z",
    totalHours: 220,
    streak: 7,
    avatar: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: 7,
    name: "liamocdonald",
    role: "Fitness Coach",
    totalWorkouts: 140,
    isActive: true,
    lastLogin: "2024-06-01T06:50:00Z",
    totalHours: 300,
    streak: 11,
    avatar: "https://i.pravatar.cc/150?img=7",
  },
  {
    id: 8,
    name: "sophialee",
    role: "Yoga Instructor",
    totalWorkouts: 70,
    isActive: false,
    lastLogin: "2024-05-29T16:10:00Z",
    totalHours: 140,
    streak: 5,
    avatar: "https://i.pravatar.cc/150?img=8",
  } ,
  {
    id: 9,
    name: "marcusknight",
    role: "CrossFit Trainer",
    totalWorkouts: 130,
    isActive: true,
    lastLogin: "2024-06-01T11:00:00Z",
    totalHours: 320,
    streak: 10,
    avatar: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: 10,
    name: "miadavis",
    role: "Pilates Instructor",
    totalWorkouts: 80,
    isActive: true,
    lastLogin: "2024-06-01T09:30:00Z",
    totalHours: 160,
    streak: 8,
    avatar: "https://i.pravatar.cc/150?img=10",
  }
];

export const addUserDetails = (
  name,
  role,
  totalWorkouts = 0,
  isActive = true,
  lastLogin = new Date().toISOString(),
  totalHours = 0,
  streak = 0,
  avatar,
) => {
  const newUser = {
    id: userData.length + 1,
    name,
    role,
    totalWorkouts,
    isActive,
    lastLogin,
    totalHours,
    streak,
    avatar,
  };
  userData.push(newUser);
  return newUser;
};

export default userData;

//done